import asyncio
from typing import AsyncGenerator, TypedDict
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, START, END

# Load environment variables (GROQ_API_KEY)
load_dotenv()

# 1. Define the graph state schema
class State(TypedDict):
    prompt: str
    response: str

# 2. Initialize the LLM with streaming enabled
llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0.7,
    streaming=True  # Crucial: enables real-time token emission from the provider
)

def model_node(state: State) -> dict:
    """Graph node that processes the user prompt and generates a response."""
    msg = llm.invoke([HumanMessage(content=state["prompt"])])
    return {"response": msg.content}

# 3. Build and compile a minimal graph workflow
builder = StateGraph(State)
builder.add_node("model_node", model_node)
builder.add_edge(START, "model_node")
builder.add_edge("model_node", END)
app = builder.compile()

# 4. Define the Server-Sent Events (SSE) Token Streamer Generator
async def sse_token_streamer(prompt_text: str) -> AsyncGenerator[str, None]:
    """
    Asynchronously streams graph execution using stream_mode='messages'.
    Intercepts raw token chunks as they are generated by the model node
    and formats them into standard SSE protocol ('data: <token>\n\n').
    """
    initial_input = {"prompt": prompt_text, "response": ""}
    
    # astream with stream_mode="messages" yields tuples of (chunk, metadata)
    async for chunk, metadata in app.astream(initial_input, stream_mode="messages"):
        
        # Filter chunks originating specifically from our model node and containing text content
        if metadata.get("langgraph_node") == "model_node" and chunk.content:
            token = chunk.content
            
            # Format according to the Server-Sent Events (SSE) standard specification
            yield f"data: {token}\n\n"
            
    # Send a standard termination signal so client-side EventSource listeners know streaming is complete
    yield "data: [DONE]\n\n"

# 5. Local execution loop for testing the SSE stream
async def main():
    print("Initializing SSE Token-by-Token Streamer Test...\n")
    test_prompt = "Explain why event-driven streaming improves user experience in modern web apps."
    
    print("--- Streaming Output (SSE Format) ---")
    async for sse_packet in sse_token_streamer(test_prompt):
        # Emits the raw formatted SSE string to stdout (simulating HTTP response stream)
        print(sse_packet, end="", flush=True)
        # Optional brief throttle to simulate realistic network streaming cadence
        await asyncio.sleep(0.01)

if __name__ == "__main__":
    asyncio.run(main())