# Import load_dotenv to read environment variables from a .env file (like API keys)
from dotenv import load_dotenv
load_dotenv()

# Import TavilySearch for built-in web search capabilities to fetch real-time data
from langchain_tavily import TavilySearch

# Import LangChain core components for creating prompts, parsing outputs, and typing chains
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import Runnable

# Import the Groq chat model wrapper from LangChain
from langchain_groq import ChatGroq

# Initialize the Tavily Search Tool
# This acts as an external retriever to pull live information from the web
# max_results=5 limits the search to the top 5 most relevant sources
search_tool: TavilySearch = TavilySearch(
    max_results=5
)

# Initialize the Groq language model
# temperature=1 makes the AI highly creative and diverse in its summarization
llm: ChatGroq = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=1,
    max_tokens=1000
)

# Create the Prompt Template
# This instructs the AI on its persona and strict constraints (e.g., no hallucination)
# The {news} placeholder will be injected dynamically with the retrieved search results
prompt: ChatPromptTemplate = ChatPromptTemplate.from_template(
    """
You are a helpful news summarization assistant.

Summarize the following search results into concise bullet points.
Do not invent facts. If information is uncertain or conflicting,
clearly indicate that.

News:
{news}
"""
)

# Build the LangChain Expression Language (LCEL) Chain
# The pipeline flows left to right: format prompt -> query LLM -> extract string content
chain: Runnable = prompt | llm | StrOutputParser()

# Execute the Tavily Search Tool directly
# This queries the internet for the specified topic and returns a list of dictionaries
news_result: list[dict[str, str]] = search_tool.run(
    "Latest 2027 upcoming news!"
)

# Invoke the LLM pipeline with the retrieved search data
# The raw search results are passed into the {news} variable of the prompt template
result: str = chain.invoke(
    {"news": news_result}
)

# Print the final summarized text generated by the AI
print(result)